=== mrfylke/frammr-mqtt-validator/specifications/device/[deviceId]/diagnostics/diagnostics.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/mrfylke/frammr-mqtt-validator/specifications/diagnostics/[deviceId]/diagnostics.schema.json",
  "title": "DeviceDiagnostics",
  "type": "object",
  "description": "Diagnostics information for specific device",

  "required": [
    "traceId",
    "eventTimestamp",
    "deviceId",

    "manufacturer",
    "model",
    "serial",
    "firmwareVersion",
    "standardVersion",
    "ipAddress",
    "label",
    "functionality",
    "status",
    "statusText"
  ],

  "properties": {
    "traceId": {
      "$id": "#/properties/traceId",
      "type": "string",
      "format": "uuid",
      "description": "An unique message identifier - UUID v4"
    },
    "eventTimestamp": {
      "$id": "#/properties/eventTimeStamp",
      "type": "string",
      "format": "date-time",
      "description": "Timestamp for the time the travelcard was read. UTC in RFC3339 format."
    },
    "deviceId": {
      "$id": "#/properties/deviceId",
      "type": "string",
      "description": "Unique device identifier. Unique for local system (in bus)"
    },

    "manufacturer": {
      "$id": "#/properties/manufacturer",
      "type": "string",
      "description": ""
    },
    "model": {
      "$id": "#/properties/model",
      "type": "string",
      "description": ""
    },
    "serial": {
      "$id": "#/properties/serial",
      "type": "string",
      "description": ""
    },
    "firmwareVersion": {
      "$id": "#/properties/firmwareVersion",
      "type": "string",
      "description": ""
    },
    "standardVersion": {
      "$id": "#/properties/standardVersion",
      "type": "string",
      "description": ""
    },
    "ipAddress": {
      "$id": "#/properties/ipAddress",
      "type": "string",
      "description": ""
    },
    "label": {
      "$id": "#/properties/label",
      "type": "string",
      "description": ""
    },
    "functionality": {
      "$id": "#/properties/functionality",
      "type": "array",
      "description": "",
      "minItems": 1,
      "items": [
        {
          "type": "string",
          "enum": ["location", "barcode", "nfc"],
          "description": ""
        }
      ]
    },
    "status": {
      "$id": "#/properties/status",
      "type": "string",
      "enum": ["OK", "ERROR", "WARNING"],
      "description": ""
    },
    "statusText": {
      "$id": "#/properties/statusText",
      "type": "string",
      "description": ""
    }
  }
}

=== mrfylke/frammr-mqtt-validator/specifications/device/[deviceId]/diagnostics/diagnostics.example.json
{
  "$schema": "./diagnostics.schema.json",
  "traceId": "543070fe-ef32-11ed-a05b-0242ac120003",
  "deviceId": "flv202400004",
  "eventTimestamp": "2023-04-22T10:28:37.337Z",
  "manufacturer": "Acme",
  "model": "NFC2000b",
  "serial": "F0A222100004",
  "firmwareVersion": "0.9.6.0",
  "standardVersion": "1.0.0",
  "ipAddress": "192.168.99.11",
  "label": "front",
  "functionality": ["nfc", "barcode"],
  "status": "OK",
  "statusText": "no errors"
}
